!git clone https://github.com/vivek28n/fake-news-detection.git

In [36]:
%cd fake-news-detection
!ls

[Errno 2] No such file or directory: 'fake-news-detection'
/content/fake-news-detection
data  notebooks  README.md  requirements.txt

In [37]:
!ls data/raw

Fake.csv  Fake.csv.zip	True.csv  True.csv.zip

In [38]:
!unzip -o data/raw/Fake.csv.zip -d data/raw/
!unzip -o data/raw/True.csv.zip -d data/raw/

Archive:  data/raw/Fake.csv.zip
  inflating: data/raw/Fake.csv
Archive:  data/raw/True.csv.zip
  inflating: data/raw/True.csv
 extracting: data/raw/Fake.csv.zip

In [39]:
!ls data/raw

Fake.csv  Fake.csv.zip	True.csv  True.csv.zip

In [40]:
import pandas as pd
import numpy as np

In [41]:
fake_df = pd.read_csv("data/raw/Fake.csv")
true_df = pd.read_csv("data/raw/True.csv")

print("Fake News Dataset Shape:", fake_df.shape)
print("True News Dataset Shape:", true_df.shape)

print("\nFake News Dataset:")
display(fake_df.head())

print("\nTrue News Dataset:")
display(true_df.head())

Fake News Dataset Shape: (23481, 4)
True News Dataset Shape: (21417, 4)

Fake News Dataset:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

True News Dataset:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [42]:
# Add labels
fake_df["label"] = 0   # Fake News
true_df["label"] = 1   # True/Real News

print("Fake News Label:", fake_df["label"].unique())
print("True News Label:", true_df["label"].unique())

Fake News Label: [0]
True News Label: [1]

In [43]:
# Combine both datasets
df = pd.concat([fake_df, true_df], ignore_index=True)

# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Combined Dataset Shape:", df.shape)
display(df.head())

Combined Dataset Shape: (44898, 5)

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1